blank_issues_enabled: false
contact_links:
  - name: 📃 文档
    url: https://github.com/revanced/revanced-documentation/
    about: 不知道如何或从哪里开始？查看我们的文档！
  - name: 🗨 订阅
    url: https://t.me/bb_show
    about: 获取最新预构建安装包，订阅更新。
